name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Set up Java
        uses: actions/setup-java@v6
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v3.5.0

      - name: Gradle build
        run: |
          ./gradlew clean test build
